### ISSUE TITLE
Cannot install pyscsi via pip

### ISSUE THREAD

**Issue by hrchu** [rosjat/python-scsi#71] opened 2018-06-29 10:51 UTC
```
(test3) seti@home:~/venv$ pip install pyscsi
Collecting pyscsi
  Downloading https://files.pythonhosted.org/packages/6a/19/5da8e1a53396fa2631024643d70cced149ba738bb9740d259cb4a251c437/PYSCSI-1.0.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 12.3MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/PYSCSI.egg-info
    writing pip-egg-info/PYSCSI.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/PYSCSI.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/PYSCSI.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/PYSCSI.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/PYSCSI.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/PYSCSI.egg-info/SOURCES.txt'
    running egg_info
    creating pip-egg-info/LINUX_SGIO.egg-info
    writing pip-egg-info/LINUX_SGIO.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/LINUX_SGIO.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/LINUX_SGIO.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/LINUX_SGIO.egg-info/SOURCES.txt'
    error: package directory 'linux_sgio' does not exist

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vts20fz0/pyscsi/
(test3)seti@home:~/venv$ uname -a
Linux 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(test3) seti@home:~/venv$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l

(test3)seti@home:~/venv$ python --version
Python 3.5.2

```

**Comment by hrchu** [comment] 2018-07-02 08:40
The package installed manually (from the master branch) works on my python 3.5 environment.

It will be nice if the pypi package works!

**Comment by rosjat** [comment] 2018-07-02 10:50
I will take a look at it later this week and try to figure it out

**Comment by pycoder-adc** [comment] 2019-02-12 04:18
I had the same problems when trying to install both pyscsi and linux_sgio via pip. The problem appears to be in the setup.py files in both packages. The setup.py files are identical and both reference the other projects packages without supplying the required files. Probably the easiest fix without munging the GitHub directories would be to modify the setup.py files for each project so it only references the packages included in that project.
@rosjat , I can submit the changes if you would like.

**Comment by rosjat** [comment] 2019-02-12 04:22
hi,

sure you are  welcome to take a shot at it. Like I said beore we never
tested this because its not a priority to get it work with pip. Most people
who use it do it for testing and they just get  the github repo

regards

markus

Am Di., 12. Feb. 2019 um 05:18 Uhr schrieb pycoder-adc <
notifications@github.com>:

**Comment by pycoder-adc** [comment] 2019-02-12 04:28
I should have left my platform and python version info just in case you are interested. I don't think they have anything to do with the issue except that I am working on a linux platform using a sgio device (glucometer).
Fedora 29
$ uname -r
4.20.6-200.fc29.x86_64
$ python --version
Python 3.7.2

**Comment by rosjat** [comment] 2019-02-12 04:39
nah it shouldnt depend on the system the only issue i got from someone was with some sony device as i remember correct but it was not relatae to the code in any way. I guess the biggest issue is the compilation of the libiscsi part since this has bindings to libiscsi and it is only a simpler version with the basic commands

**Comment by pycoder-adc** [comment] 2019-02-12 04:57
Hi Markus,
I tried the github repo first and that doesn't work for some reason. The setup.py build and install don't show any errors but it when I try to do a linux_sgio.open call I get an error. I just did a clean 'git clone' attempt again and here is the result I get for a simple interactive python test (I was getting the same error when using the "glucometer.py" package that imports pyscsi and linux_sgio.

(myWorkingDir) [adc@asusl python-scsi]$ python3
Python 3.7.2 (default, Jan 16 2019, 19:49:22) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyscsi
>>> import linux_sgio
>>> my_fd=linux_sgio.open("/dev/sg3",1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'linux_sgio' has no attribute 'open'
>>> 

Something appears to be wrong with the build of linux_sgio such that the underlying '.c' functions are not found in the library at runtime. That's my guess at any rate. This problem is more opaque to me and could have to do with SWIG which I haven't worked with for many years.

If I build the the two libraries separately via the pip downloads, then everything works.
cheers,
Alan

**Comment by rosjat** [comment] 2019-02-12 05:04
i need to check that because the sgio package should work even with python3 but since this is not a pure python3 package and i just did basic testing with python3 it might be related to the  c code that gets compiled for python3. 

i really need to do a python3 package i guess -.-

**Comment by furas** [comment] 2019-02-16 23:23
I also get this error with Python 3.7.2. 

> AttributeError: module 'linux_sgio' has no attribute 'open'

There is missing "dot" between `from` and `linux_sgio` in `linux_sgio/__init__.py` in line

    from .linux_sgio import *

Without "dot" it imports the same `linux_sgio/__init__.py` instead of module created with C.

Code from repo doesn't have this dot but code from `pip3.7 download linux_sgio` has this dot.

Code works without error if I add "dot" manually or using `sed` like this:

    git clone https://github.com/rosjat/python-scsi
    cd python-scsi

    sed -i 's/ linux_sgio/ .linux_sgio/' linux_sgio/__init__.py

    python3 setup.py build
    python3 setup.py install

Few days ago I described it also in [glucometerutils: Problem with otverio2015 driver](https://github.com/Flameeyes/glucometerutils/issues/44)

**Comment by rosjat** [comment] 2019-02-16 23:35
Yeah the dot is an issue on python3 there is a commit for it wyiting but
never gibt to check it for 2.7  so i legt it for now

Am So., 17. Feb. 2019, 09:23 hat furas <notifications@github.com>
geschrieben:

**Comment by pycoder-adc** [comment] 2019-02-17 00:51
I can confirm that the fix as described by @furas solves the problems I was having with `linux_sgio` on Python 3.7.2

**Comment by rosjat** [comment] 2019-02-17 01:04
For relative Imports it should fix it with Python 3 for 2.7 i need to
confirm it but i think it should work there too. The pull request by hrchu
would fix this but lije i said i dient hat time to confirm and test it with
Python 2.7 and since we need to be kompatible for now i need to do at leat
basic testing

Am So., 17. Feb. 2019, 10:51 hat pycoder-adc <notifications@github.com>
geschrieben:

**Comment by furas** [comment] 2019-02-17 15:57
I still have Python 2.7 so I started testing it and finally I created script which can test with different versions and with or without dot.

It creates new venv (using `venv` in Python3 or `virtualenv` in Python2), clones code from repo, adds dot, builds and installs code, uses python to check `linux_sgio.open` (and `linux_sgio.__file__` to confirm that it uses module from venv). Everytime you run script it deletes old venv and code from repo so it always run with fresh data.

As default it tests for Python 2.7 without adding dot.

    $ script.sh

You can add python version as first argument (ie. 2.7, 3.6, 3.7) and it tests with this version but still without dot

    $ script.sh 3.7

You can add dot as second argument to test code with dot

    $ script.sh 3.7 .

    $ script.sh 2.7 .

Tests show me it works with dot in 2.7, 3.6, 3.7. I already don't have 2.6 and 3.5 to test it with older versions.

**script.sh**

    #!/bin/bash

    if [ "$1" != "" ]; then
       VERSION=$1
    else
       VERSION=2.7
    fi

    if [[ "${VERSION}" == 2* ]]; then # 2 or 2.7
       #sudo python2.7 -m pip install -U virtualenv
       VENV=virtualenv
    else
       #built-in module (at least in 3.7+)
       VENV=venv
    fi

    echo
    echo "[INFO] Python: ${VERSION}"
    echo "[INFO] Venv: ${VENV}"
    echo "[INFO] Add dot:" $(if [ "$2" == "." ]; then echo "True"; else echo "False"; fi)
    echo

    # remove old version
    echo
    echo "[INFO] remove old folders"
    echo

    rm -r venv
    rm -r python-scsi

    # create new venv
    echo
    echo "[INFO] create venv"
    echo

    python${VERSION} -m ${VENV} venv
    . venv/bin/activate

    # download new code
    echo
    echo "[INFO] clone code"
    echo

    git clone https://github.com/rosjat/python-scsi
    cd python-scsi

    # modify (or not)
    if [[ "$2" == "." ]]; then
       echo
       echo "[INFO] add dot"
       echo

       sed -i 's/ linux_sgio/ .linux_sgio/' linux_sgio/__init__.py
    fi

    # build
    echo
    echo "[INFO] build"
    echo

    python${VERSION} setup.py build

    # install
    echo
    echo "[INFO] install"
    echo

    python${VERSION} setup.py install

    # back to parent folder so Python will not use code from local folder linux_sgio.
    cd ..

    # test
    echo
    echo "[INFO] tests"
    echo
    echo "[INFO] cat venv/lib/python${VERSION}/site-packages/linux_sgio/__init__.py"
    echo

    cat venv/lib/python${VERSION}/site-packages/linux_sgio/__init__.py

    echo
    echo "[INFO] python: linux_sgio.__file__ and linux_sgio.open"
    echo

    python${VERSION} -c "import linux_sgio; print('linux_sgio.__file__: ' + linux_sgio.__file__); print('linux_sgio.open    : ' + str(linux_sgio.open))"

**Comment by rosjat** [comment] 2019-02-17 23:38
cool can you make a pull request for it and maybe put it in python-scsi/tests ?

**Comment by rosjat** [comment] 2019-12-13 13:54
hi guys i will close this now, oi just took a look at the whole pypi thing and its just to much of tweaking around to get this going. You cant really package the whole project since we need to ship binaries when we package for pypi and they dont want binaries (and i am to uninterested in taking a look at manylinux). The other solution was the effort i made to put a 2.7 package there and seperate stuff and do a lot of extra work that needs to be maintained not in this project at all in my opinion. so if one of you like to take a shot at bootstaping this whole thing for a pypi solution do so but i wont stress it any further.

cheers

MArkus

**Closed by rosjat** 2019-12-13 13:54 UTC
